#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Advent of code 2021, day $DAY
blackstream-x’ solution
"""


import logging

import helpers


@helpers.timer
def part1(reader):
    """Part 1"""
    result = None
    for line in reader.lines():
        ...
    #
    return result


@helpers.timer
def part2(reader):
    """Part 2"""
    result = None
    for line in reader.lines():
        ...
    #
    return result


if __name__ == "__main__":
    helpers.solve_puzzle(part1, part2)


# vim: fileencoding=utf-8 sw=4 ts=4 sts=4 expandtab autoindent syntax=python:
